spring:
  profiles:
    active:
    - dev

---
server:
  port: 8201
spring:
  profiles: dev		#开发环境
  application:
    name: exam-config-client

#Eureka配置
eureka:
  client:  #将客户端注册到服务端
    service-url:
      defaultZone: http://exam-eureka-1:7001/eureka

---
server:
  port: 8202
spring:
  profiles: test	#测试环境
  application:
    name: exam-config-client

#Eureka配置
eureka:
  client:  #将客户端注册到服务端
    service-url:
      defaultZone: http://exam-eureka-1:7001/eureka