spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: exam-config-house-client
  datasource:
    druid:
      url: jdbc:mysql://192.168.54.20:3306/houses?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.lesheng.pojo
  mapper-locations: classpath:mapper/*.xml

#Eureka配置
eureka:
  client:  #将客户端注册到服务端
    service-url:
      defaultZone: http://exam-eureka-1:7001/eureka,http://exam-eureka-2:7002/eureka,http://exam-eureka-3:7003/eureka
  instance:
    instance-id: exam-house-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

#info配置
info:
  app.name: lesheng-exam
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: exam-config-house-client
  datasource:
    druid:
      url: jdbc:mysql://192.168.54.20:3306/houses?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.lesheng.pojo
  mapper-locations: classpath:mapper/*.xml

#Eureka配置
eureka:
  client:  #将客户端注册到服务端
    service-url:
      defaultZone: http://exam-eureka-1:7001/eureka,http://exam-eureka-2:7002/eureka,http://exam-eureka-3:7003/eureka
  instance:
    instance-id: exam-house-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

#info配置
info:
  app.name: lesheng-exam
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$