spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001 #注册中心占用7001端口
spring:
  profiles: dev
  application:
    name: exam-config-eureka-client

eureka:
  instance:
    hostname: exam-eureka-1 #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端是注册中心，本程序的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置eureka server交互地址

---
server:
  port: 7001 #注册中心占用7001端口
spring:
  profiles: test
  application:
    name: exam-config-eureka-client

eureka:
  instance:
    hostname: exam-eureka-1 #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己端是注册中心，本程序的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置eureka server交互地址